version: '3.8'

services:
  video-rental-store-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:6001;http://+:6000

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  app-network:
    driver: bridge
