version: '3.8'

services:
  video-rental-store-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: video-rental-store-app:latest
    ports:
      - "6000:80"  
      - "6001:443" 
    depends_on:
      - mongodb
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
